### ISSUE TITLE
IOarena issue: Why MDBX significally slower (2K RPS) in the "lazy" mode in comparison with LMDB (150K RPS).

### ISSUE THREAD

**Issue by azhmur** [erthink/libmdbx#104]
I have tried to reproduce some tests mentioned in ReadMe with ioarena and it looks kind of broken right now.
Environment: Ubuntu 18 LTS on Azure 16 GiB RAM.

1) get test fails for big operations count. (Out of Memory?)

```
IOARENA (embedded storage benchmarking)

configuration:
  engine       = mdbx
  datadir      = ./_ioarena
  benchmark    = get
  durability   = lazy
  wal          = indef
  operations   = 10000000
  key size     = 16
  value size   = 32
  binary       = no
  batch length = 500
  continuous   = no

key-gen: using 24 bits, up to 10000000 keys
doer.0: {get}, key-space 0, key-sequence 0
error: key nAg5meqsPB4reia5 not found (get, #0, 0+0)
error: mdbx_txn_abort, MDBX_BAD_TXN: Transaction is not valid for requested operation, e.g. had errored and be must aborted, has a child, or is invalid (-30782)
```

2) set test in lazy mode seems doing a lot of fsync. giving numbers close 2k rps, while sync has 250 rps.

PS lmdb have same failure in first case, but works much better in second case giving 150k RPS.

**Comment by azhmur** [comment]
Get through first issue. It seems both lmdb and mdbx becomes poisoned with data from previous run in get test. So workaround is to run set tests completely and then run get test.

**Comment by erthink** [comment]
1. _IOarena_ intentionally does not implement "clean startup" in order to be able to use the DB state after previous runs, and this is used in many benchmark scenarios. So, _"It's Not a Bug, It's a Feature"_ :)
2. In many cases LMDB and MDBX shows the same performance with differences mainly for four reasons:
   - `MDBX_LIFORECLAIM` may give significant (1.5-10 times) write-performance boost on systems with write-back disk cache.
   - MDBX spends slightly less CPU clock time on internal data processing (e.g. sorting and searching). Therefore, it faster (up to 20%) in data modification scenarios where disk I/O is not a bottleneck (otherwise the difference is not noticeable).
   - To avoid crashes and heisenbugs MDBX performs more checks for parameters and internal state. Therefore, MDBX is slower in some scenarios with little work inside the DB (i.e.getting the current record or read-only iterating).
   - Due to differences in operating modes: `MDBX_NOSYNC_SAFE` != `MDB_NOSYNC`, on Windows (MDBX uses `LockFileEx()`), on MacOS (MDBX uses `fcntl(F_FULLFSYNC)`).

Going back to your question about the 2K/150K RPS difference in the "lazy" mode:
   - In the IOarena source code you can see that in the "lazy" mode `MDB_NOSYNC` for LMDB but `MDBX_SAFE_NOSYNC` for MDBX are used. This explains the difference.
   - The reason for this difference (among other things) is to show how the durability guarantee affects speed, but not just the superiority of MDBX. However, you can made changes and compare performance in the modes you are interested in.
   - i.e. IOarena is a tool to play, you should known what you want to benchmark and how it really works.

**Comment by azhmur** [comment]
Thank you for clear explanations. I read through header about MDBX_SAFE_NOSYNC vs MDBX_UTTERLY_NOSYNC and still do not get why MDBX_SAFE_NOSYNC seems to be blocked by flashes. Documentation seems to be more focused on higher memory usage related to this mode. 
Running 'ioarena -D mdbx -B set -n 10000' with '-m sync' or '-m lazy' gives same performance showing each of operations was waiting for flush.

![image](https://user-images.githubusercontent.com/2143587/82119969-93d16780-977a-11ea-93ec-cbeab1e0a99f.png)
![image](https://user-images.githubusercontent.com/2143587/82119989-bd8a8e80-977a-11ea-8170-3ed45299c416.png)

**Comment by erthink** [comment]
@azhmur, Suggest you should (re)check your source, changes, script, config, etc.., and then (re)run the benchmark.

For instance my local test:
```
$ ./@BUILD/src/ioarena -D mdbx -B set -n 100000 -m lazy
IOARENA (embedded storage benchmarking)

configuration:
  engine       = mdbx
  datadir      = ./_ioarena
  benchmark    = set
  durability   = lazy
  wal          = indef
  operations   = 100000
  key size     = 16
  value size   = 32
  binary       = no
  batch length = 500
  continuous   = no

key-gen: using 24 bits, up to 100000 keys
doer.0: {set}, key-space 0, key-sequence 0
     time | bench      rps      min       avg       rms       max       vol           #N
    0.975 |   set: 102.533K   5.084us   9.559us   9.634us 134.741us   4.922Mbps 100.000K
complete.

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> set(100000)
[ltn_from     ltn_to   ]       ops_count       %        p%
----------------------------------------------------------
[   5.000us,   5.999us ]              62   0.06%   0.0620%
[   6.000us,   6.999us ]             109   0.11%   0.1710%
[   7.000us,   7.999us ]            7365   7.37%   7.5360%
[   8.000us,   8.999us ]            2861   2.86%  10.3970%
[   9.000us,   9.999us ]           82926  82.93%  93.3230%
[  10.000us,  11.999us ]            3081   3.08%  96.4040%
[  12.000us,  13.999us ]            1482   1.48%  97.8860%
[  14.000us,  15.999us ]            1794   1.79%  99.6800%
[  16.000us,  17.999us ]             247   0.25%  99.9270%
[  18.000us,  19.999us ]              40   0.04%  99.9670%
[  20.000us,  24.999us ]              28   0.03%  99.9950%
[  25.000us,  29.999us ]               3   0.00%  99.9980%
[  50.000us,  59.999us ]               1   0.00%  99.9990%
[ 120.000us, 139.999us ]               1   0.00% 100.0000%
----------------------------------------------------------
total:       955.954ms            100000
min latency:   5.084us/op
avg latency:   9.559us/op
rms latency:   9.634us/op
max latency: 134.741us/op
 throughput: 102.551Kops/s

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> rusage
iops: read 0, write 16800, page 0
cpu: user 0.466845, system 0.508239
space: disk 64.007812, ram 0.006157
```

With the diff from IOarena master branch (`167a5e0318d425a714a53430d702c84081e9e2d1`):
```diff
diff --git a/runme.sh b/runme.sh
index f595e99..07d83ee 100755
--- a/runme.sh
+++ b/runme.sh
@@ -12,16 +12,16 @@ DIR=@BUILD
 echo "*** run cmake..."
 mkdir -p $DIR && \
 	(cd $DIR && cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo .. \
-	-DENABLE_ROCKSDB=ON \
-	-DENABLE_FORESTDB=ON \
-	-DENABLE_SOPHIA=ON \
-	-DENABLE_WIREDTIGER=ON \
+	-DENABLE_ROCKSDB=OFF \
+	-DENABLE_FORESTDB=OFF \
+	-DENABLE_SOPHIA=OFF \
+	-DENABLE_WIREDTIGER=OFF \
 	-DENABLE_LMDB=ON \
 	-DENABLE_MDBX=ON \
-	-DENABLE_LEVELDB=ON \
-	-DENABLE_SQLITE3=ON \
-	-DENABLE_VEDISDB=ON \
-	-DENABLE_IOWOW=ON \
+	-DENABLE_LEVELDB=OFF \
+	-DENABLE_SQLITE3=OFF \
+	-DENABLE_VEDISDB=OFF \
+	-DENABLE_IOWOW=OFF \
 	) || exit 1
 
 echo "*** run make..."
diff --git a/src/drivers/ia_mdbx.c b/src/drivers/ia_mdbx.c
index 96296ae..32212c4 100644
--- a/src/drivers/ia_mdbx.c
+++ b/src/drivers/ia_mdbx.c
@@ -52,7 +52,7 @@ static int ia_mdbx_open(const char *datadir) {
     modeflags = MDBX_LIFORECLAIM;
     break;
   case IA_LAZY:
-    modeflags = MDBX_SAFE_NOSYNC | MDBX_NOMETASYNC;
+    modeflags = MDBX_UTTERLY_NOSYNC | MDBX_NOMETASYNC;
     break;
   case IA_NOSYNC:
     modeflags = MDBX_WRITEMAP | MDBX_UTTERLY_NOSYNC;
```

**Comment by azhmur** [comment]
Please forgive my ignorance. I was looking for some option in between of "we can write fast and loose everything" and "we syncing all writes and do it slowly". Like loose small amount of data, but not everything, while still having rather good update throughput. (fsync=off in WAL based systems) But it seems MDBX_SAFE_NOSYNC is close to MDBX_SAFE_SYNC in both performance and durability (at least on azure block device), while all less strict options are risking not only some updates will be lost, but total corruption.

**Comment by erthink** [comment]
Some points for clarity (with simplification):

The page dirty/altering rate will be the same for all "sync"-modes. This is true for (almost?) any page-based database. I.e. when we make some update of data, we alter (aka make dirty) some pages inside database. Further we should ever write those pages to the disk. If we don't have/use WAL then we should write all dirty pages on every commit.

Both in `MDBX_SAFE_NOSYNC` and `MDBX_UTTERLY_NOSYNC` modes MDBX make all such writes at every commit, but don't call `fdatasync()`. So I/O bandwidth generated by an application will be the same. However, it is a big difference how MDBX handle pages with previous data versions (i.e. already used pages):
   - In then `MDBX_UTTERLY_NOSYNC` mode MDBX overwrites any already used page which don't (and couldn't be) used  by some reader. When many transaction committed a lot of pages has overwrites many times (e.g. the top of b+tree). Such overwrites may be merged/eliminates by kernel, if filesystem was not configured to preserve write-order (aka data order) for user data.
On the other hand, any system failure after such write-reorder will cause (likely a whole) database corruption, since part of the pages that makes up the tree will be with invalid obsolete data that was written to these pages before the last version of the tree was formed.
   - In the `MDBX_SAFE_NOSYNC` mode MDBX allocated news pages instead of overwriting it. Thus MDBX as though preserve write-order from b+tree structure point of view, and in case of system failure only unsaved data will be lost. On the other hand, allocation new pages increase database size and/or process [working set size](https://en.wikipedia.org/wiki/Working_set_size) and so on.

**Comment by erthink** [comment]
Some reference records on my old notebook:
```
$ make bench-quartet
sed \
	-e "s|@MDBX_GIT_TIMESTAMP@|2020-05-28T00:42:15+03:00|" \
	-e "s|@MDBX_GIT_TREE@|ae35484abbdb4a570e626294b65283e108c371cf|" \
	-e "s|@MDBX_GIT_COMMIT@|c9f461c4ebfdcff2fdbc3b2b76ec45de16d4a124|" \
	-e "s|@MDBX_GIT_DESCRIBE@|v0.7.0-135-gc9f461c4e|" \
	-e "s|\${MDBX_VERSION_MAJOR}|0|" \
	-e "s|\${MDBX_VERSION_MINOR}|7|" \
	-e "s|\${MDBX_VERSION_RELEASE}|0|" \
	-e "s|\${MDBX_VERSION_REVISION}|2077|" \
src/version.c.in > src/version.c
(echo '#define MDBX_BUILD_TIMESTAMP "2020-05-28T03:05:13+0300"' \
&& echo '#define MDBX_BUILD_FLAGS "-O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -Wl,--gc-sections,-z,relro,-O1  -lrt "' \
&& echo '#define MDBX_BUILD_COMPILER "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0"' \
&& echo '#define MDBX_BUILD_TARGET "x86_64-linux-gnu"' \
&& echo '#define MDBX_BUILD_SOURCERY 2a89a807633ce0477483ede568478c8807b5f9041cdf1556e6ed18c2b2800e82_v0_7_0_135_gc9f461c4e' \
) > src/config.h
cc -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  -DNDEBUG=1 '-DMDBX_CONFIG_H="config.h"' -DLIBMDBX_EXPORTS=1 -c src/alloy.c -o mdbx-dylib.o
cc -O2 -g -Wall -Werror -Wextra -Wpedantic -ffunction-sections -fPIC -fvisibility=hidden -std=gnu11 -pthread -Wno-error=attributes  mdbx-dylib.o -pthread -shared -Wl,--gc-sections,-z,relro,-O1  -lrt  -o libmdbx.so
LD_LIBRARY_PATH="./:${LD_LIBRARY_PATH}" ../ioarena/@BUILD/src/ioarena -D mdbx -B crud -m nosync -n 25000000 | tee bench-mdbx_25000000.txt | grep throughput && LD_LIBRARY_PATH="./:${LD_LIBRARY_PATH}" ../ioarena/@BUILD/src/ioarena -D mdbx -B get,iterate -m sync -r 4 -n 25000000 | tee -a bench-mdbx_25000000.txt | grep throughput || mv -f bench-mdbx_25000000.txt bench-mdbx_25000000.txt.error
 throughput: 109.899Kops/s
 throughput:  19.471Mops/s
 throughput:   1.482Mops/s
LD_LIBRARY_PATH="./:${LD_LIBRARY_PATH}" ../ioarena/@BUILD/src/ioarena -D lmdb -B crud -m nosync -n 25000000 | tee bench-lmdb_25000000.txt | grep throughput && LD_LIBRARY_PATH="./:${LD_LIBRARY_PATH}" ../ioarena/@BUILD/src/ioarena -D lmdb -B get,iterate -m sync -r 4 -n 25000000 | tee -a bench-lmdb_25000000.txt | grep throughput || mv -f bench-lmdb_25000000.txt bench-lmdb_25000000.txt.error
 throughput:  97.269Kops/s
 throughput:  20.585Mops/s
 throughput:   1.511Mops/s
LD_LIBRARY_PATH="./:${LD_LIBRARY_PATH}" ../ioarena/@BUILD/src/ioarena -D rocksdb -B crud -m nosync -n 25000000 | tee bench-rocksdb_25000000.txt | grep throughput && LD_LIBRARY_PATH="./:${LD_LIBRARY_PATH}" ../ioarena/@BUILD/src/ioarena -D rocksdb -B get,iterate -m sync -r 4 -n 25000000 | tee -a bench-rocksdb_25000000.txt | grep throughput || mv -f bench-rocksdb_25000000.txt bench-rocksdb_25000000.txt.error
 throughput:  40.953Kops/s
 throughput:   5.847Mops/s
 throughput: 116.550Kops/s
LD_LIBRARY_PATH="./:${LD_LIBRARY_PATH}" ../ioarena/@BUILD/src/ioarena -D wiredtiger -B crud -m nosync -n 25000000 | tee bench-wiredtiger_25000000.txt | grep throughput && LD_LIBRARY_PATH="./:${LD_LIBRARY_PATH}" ../ioarena/@BUILD/src/ioarena -D wiredtiger -B get,iterate -m sync -r 4 -n 25000000 | tee -a bench-wiredtiger_25000000.txt | grep throughput || mv -f bench-wiredtiger_25000000.txt bench-wiredtiger_25000000.txt.error
 throughput: 147.400Kops/s
 throughput:   2.422Mops/s
 throughput: 789.814Kops/s
```
