### ISSUE TITLE
Provide LMDB API compatibility header

### ISSUE THREAD

**Issue by jserv** [erthink/libmdbx#107]
Since there are various applications using LMDB, it would be great if libmdbx can provide LMDB API compatibility headers to ease porting efforts.

**Comment by erthink** [comment]
Such header couldn't be implemented in 100% right way since cursors and dbi-handles have different lifetime in MDBX. At first sight these are small differences, but they can lead to memory leaks or difficult-to-detect errors.

Thus, such header will be a false premise about compatibility. This circumstance was also the reason for the original decision to make MDBX API incompatible with LMDB.

On the other hand, it is only three reasons to migrate from LMDB to MDBX:
1. if some MDBX feature(s) is required which is not supported by LMDB.
2. if some LMDB bug affects to your use case, actually it is rare.
3. If there is some error in your code, but you can't locate it because of weak control inside LMDB.

Each of these reasons justifies the effort required to migrate from LMDB to MDBX.
