### ISSUE TITLE
Is there an example showing the use of MDBX_FIRST_DUP, MDBX_NEXT_DUP, MDBX_LAST_DUP?

### ISSUE THREAD

**Issue by RallyTronics** [erthink/libmdbx#109]
Is there an example showing these cursor operations?

If I call mdbx_cursor_get(..., MDBX_LAST_DUP) is the data available? or do I have to call mdbx_cursor_get(..., MDBX_GET_CURRENT) afterwords before the data is valid?

In other words do the MBDX_xxx_DUP operations return key/data?

**Comment by erthink** [comment]
> Is there an example showing these cursor operations?

The set of these operations historically comes from Berkeley DB API.
So, you can refer to most of Berkeley DB examples and [API description](https://web.stanford.edu/class/cs276a/projects/docs/berkeleydb/ref/am_conf/dup.html).

There are no corresponding examples for MDBX, as well as any tutorial, since I do not have the resources (free time) to create and maintain them. However, I will be happy to accept such [PR](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests).

> If I call mdbx_cursor_get(..., MDBX_LAST_DUP) is the data available? or do I have to call mdbx_cursor_get(..., MDBX_GET_CURRENT) afterwords before the data is valid?

Data is returned when all cursor seek operations are completed successfully.

> In other words do the MBDX_xxx_DUP operations return key/data?

Yes.

-----

It will be great if you do a PR with fixing similar flaws in the API description, since ones are only visible to the fresh eye.

**Comment by RallyTronics** [comment]
I will try to go through all of the comments in mdbx.h over the next week or so and add clarification, correct spelling, etc.  I will leave this open for when I need to ask more questions as I go through it.

**Comment by RallyTronics** [comment]
I am new to this sort of database and don't yet have a good handle on transactions.   I understand that there can be only 1 transaction active per thread.  Does this infer that there is only 1 transaction active per environment in an application?

**Comment by erthink** [comment]
> I am new to this sort of database and don't yet have a good handle on transactions. I understand that there can be only 1 transaction active per thread. Does this infer that there is only 1 transaction active per environment in an application?

1. No more than one write-transaction at the same time per environment. I.e. write transactions are strongly serialized in MDBX.

2. Abilities of read-transactions depends of the `MDBX_NOTLS` option:
   - **Without** `MDBX_NOTLS` option (transactions are tied to threads): No more than one read-transaction at the same time per thread. This is recommended.
   - **With** `MDBX_NOTLS` option (transactions are NOT tied to threads): No above limitation, but you must know exactly what you are doing, otherwise you will get deadlocks or reading an alien data.

**Comment by RallyTronics** [comment]
In the MDBX_cursor_op enum:

`MDBX_GET_BOTH_RANGE, /* MDBX_DUPSORT-only: position at key, nearest data. */`

What is the definition of _nearest data_?

**Comment by RallyTronics** [comment]
What happens if you call mbdx_del and pass a nullptr for the data parameter if the database was created with the MDBX_DUPSORT flag?  Will it delete all records with the given key?

**Comment by erthink** [comment]
> In the MDBX_cursor_op enum:
> 
> `MDBX_GET_BOTH_RANGE, /* MDBX_DUPSORT-only: position at key, nearest data. */`
> 
> What is the definition of _nearest data_?

This flaw originated at the LMDB API description.
In this and other similar cases means a "lower_bound" partitioning, i.e. position at given key and at first data greater than or equal to specified data.

**Comment by erthink** [comment]
> What happens if you call `mdbx_del()` and pass a `nullptr` for the data parameter if the database was created with the `MDBX_DUPSORT` flag? Will it delete all records with the given key?

Yes, if `data` is `NULL` then all records with the given key will be deleted.

**Comment by erthink** [comment]
@RallyTronics, thanks for reporting. Now these inaccuracies are corrected.

**Comment by hyc** [comment]
> In the MDBX_cursor_op enum:
> 
> `MDBX_GET_BOTH_RANGE, /* MDBX_DUPSORT-only: position at key, nearest data. */`
> 
> What is the definition of _nearest data_?

It is the same meaning as documented in the SET_RANGE operation

**Comment by erthink** [comment]
@RallyTronics, please see [`mdbx::move_operation`](https://github.com/erthink/libmdbx/blob/devel/mdbx.h%2B%2B#L2513-L2533) from the new [C++ API](https://erthink.github.io/libmdbx/mdbx_8h_09_09.html).
