### ISSUE TITLE
mdbx_dbi_stat: returns error that "database is not compatible with the requested operation or the specified flags"

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#145]
"mdbx_dbi_stat: MDBX_INCOMPATIBLE: Environment or database is not compatible with the requested operation or the specified flags"

It's just usual DBI - created with 0 flags.

I can't reproduce it in hand-made tests (but reproducable in real DB) - because don't understand nature of the problem (usually such error coming only from mdbx_dbi_open or mdbx_env_open).

**Comment by AskAlexSharov** [comment]
Some not very useful context:
1. I migrating db from LMDB to MDBX with flags: WriteMap | NoMemInit | NoReadahead | Coalesce | Durable
2. Closing DB
3. Opening db with NoReadahead | Coalesce | Durable
4. Trying to drop 1 DBI (which was DupSort - not sure how to get current DBI flags - mdbx_dbi_flags requires to open DBI first and to open need to know flags) and  by migration - but opening this DBI with 0 flag to drop it (no special reason, just our app was written this way - and during development I changed dup-sort to non-dupsort in code - however when I trying to do same in tests - mdbx_dbi_open returns error, but on real DB) 

Probably I need change logic of our app to: 
- try to open DBI with MDBX_DB_ACCEDE
- if can't - then open with Create|flags-form-app-code

**Comment by erthink** [comment]
I have analyzed the code and have not yet found any flaws that could lead to the described problem.
However, I think I need to clarify some of the subtleties of the API that should be considered.

1. Yes, sure, you should use `MDBX_DB_ACCEDE` to open existing sub-DB without knowledge of it's DB-flags.
2. libmdbx (and LMDB) shares DBI-handles across transactions to avoid re-open ones from each transaction, and thus creates some side-effects. For instance let's look at this scenario:
- in the database there is a some named "FOO" non-dupsort sub-DB;
- you open this subDB in a read-transaction and complete it;
- you start a write transaction and do something, this transaction will knowing a DBI-handle of "FOO" but it will be in a stale/unfetched state until be used;
- at the same time you start another read transaction, this transaction also will knowing a DBI-handle of "FOO" but it also will be in a stale/unfetched state until be used;
- then you drop (and may be re-create "FOO" as the dupsort) while a above read transaction still running;
- now if you accessed from read transaction to "FOO" by known DBI-handle you will get `MDBX_BAD_DBI` (if "FOO" was just dropped) or `MDBX_INCOMPATIBLE` (if "FOO" was re-created with different DB-flags).
- So, this may seem strange and inconvenient, but it is a compromise with minimal losses for the API inherited from LMDB (and will be fixed in _MithrilDB_).
