### ISSUE TITLE
MDBX_BAD_VALSIZE when insert into empty DupSort bucket

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#146]
Simplified pseudocode to describe what's happening:
- open write transaction
- open DBI Create|DupSort
- PUT NoOverwrite: bd174f45fb00f7905ce254c0ef491691c955a15fdf10c5665b4493a591627fbe,020164
- PUT NoOverwrite: f22bb46edf31af855938befaa870ed3d86a4ad93a9ecf7c63ceaa80daea9ac4d,02081bc18080c0525000
- PUT NoOverwrite: 00bf49f440a1cd0527e4d06e2765654c0f56452257516d793a9b8d604dcfdf2a,030101087fffece68e75af9b
- Commit
- Open write transaction
- drop dbi
- open dbi Create|DupSort
- PUT NoOverwrite: bd174f45fb00f7905ce254c0ef491691c955a15fdf10c5665b4493a591627fbe, 0201c8
- last put returns error: mdbx_cursor_put: MDBX_BAD_VALSIZE: Invalid size or alignment of key or data for target database, either invalid subDB name
- if enable assertions I will see next assertion (app does call rollback because error above happened):
Assertion failed: (stage == MDBX_MC_LIVE || (stage == MDBX_MC_WAIT4EOT && bk)), function mdbx_cursors_eot, file mdbx, line 8947.

This error is reproducible in our (a bit complex) test, but I can't isolate problem / write smaller test which does trigger problem.

**Comment by erthink** [comment]
1. [This assertion](https://github.com/erthink/libmdbx/blob/3e7459b428373404e3c8ce238bd4061fa9d18f79/src/core.c#L5915-L5916) is always enabled to check an integrity of cursor's and txn's internals during commit.
2. In your case the `MDBX_BAD_VALSIZE` will returned if length of a key and/or a value is out of min/max bounds for particular DBI. However, the error will also be returned if the cursor's internals or related structures are damaged.
3. Since we see the noted assertion then we should suggest that `MDBX_BAD_VALSIZE` is the result of damage to the cursor's internals and/or related structures.

Currently, cursors are well tested in libmdbx' tests, including stochastic scenarios with intensive use of nested transactions.
So for now, I'm inclined to think that the problem is caused by some error in your code, although I don't rule out errors in libmdbx.

Please analyze your code for simultaneous use of cursors from different threads, especially the `mdbx_cursor_close()` function.
For my part, I will try to add additional control to this function to catch such situations.

**Comment by AskAlexSharov** [comment]
Thank, i will search for concurrency. (I also noticed when adding some debug prints - problem gone - so, for sure some concurrency there)

**Comment by AskAlexSharov** [comment]
reason was: 
- when APP re-creating DBI - it storing new DBI value in own memory 
- but there was rollback of transaction which did re-creation of DBI (it's fine - because it's logic of some tests)
- as a result app had wrong DBI value in memory and used it

**Comment by erthink** [comment]
@AskAlexSharov, thank you for your investigation and clarification.
However, this is still a bug, because in the described scenario, the library allows the use of an incorrect DBI handle.

**Comment by erthink** [comment]
@AskAlexSharov, could you undo fixes of your code and retry tests on the `fix-146` branch, i.e. test my fixes?

**Comment by AskAlexSharov** [comment]
I did: 
Assertion failed: (!"Invalid key-size"), function mdbx_cursor_put, file mdbx, line 15767.

**Comment by erthink** [comment]
Thanks, i'll dig further.

Can you point me to the your fix?
Maybe this will help me reproduce the problem locally.

**Comment by AskAlexSharov** [comment]
FIX: just deleted all records from DBI manually instead of drop+create DBI. 

I can't reproduce in small test (big one is too confusing), but here is small test which also shows some err (on fix-146) - DBI value doesn't change after re-create and abort, but I can't use it: MDBX_BAD_DBI: The specified DBI-handle is invalid or changed by another thread/transaction [recovered]:  
https://github.com/ledgerwatch/turbo-geth/blob/mdbx_rollback_of_drop/ethdb/mdbx/txn_test.go#L279

**Comment by erthink** [comment]
1. I hope that the last commit I fixed the problem.
The error was that the check for the use of the re-created handle was too late.
So, checking the length of the key and data could result in an error, since the internal data was reset during handle renewing.
2. Your code is not good, especially the fix.
Instead of drop and re-creating DBI or deleting all records manually, you could just call mdbx_drop(tx, dbi, false) to purge data but leave both key-value table and it's handle.

**Comment by AskAlexSharov** [comment]
1. Don't see difference in my test
2. Agree.

**Comment by erthink** [comment]
1. I [reproduced](https://github.com/erthink/libmdbx/commit/760f1654c2371306d07fbeefdcfd18f87e80358c#diff-666c97bb6985469288a46d459a55b6d2af713b4b36e577181c7946f5e5fda0b4R36-R73) a scenario of your test and could not get the `MDBX_BAD_VALSIZE`, but only `MDBX_BAD_DBI`.
2. As I wrote earlier, to get rid of the need to re-open (or close) DBI handles in each transaction, they are shared across transactions. In other words, the handle that is opened in one transaction becomes available in others, and the one get closed becomes unavailable everywhere. This is quite convenient and reasonable with two additional provisions:
   - The handle does not become available (for other transactions) until the transaction commit if the handle is related a newly created key-value table. This provision IS enforced.
   - The handle still available (for other transactions) until the transaction commit if the handle is related a dropped key-value table. This provision is NOT enforced and this may be a subject to fix.

So, in your scenario, the `MDBX_BAD_DBI` error occurs because (the current behavior of libmdbx is) the handle becomes unavailable immediately after dropping the table and remains closed even when this transaction is canceled (although the table is saved in this case). Technically, to fix this, it is enough to [open a DBI-handle again](https://github.com/erthink/libmdbx/commit/760f1654c2371306d07fbeefdcfd18f87e80358c#diff-666c97bb6985469288a46d459a55b6d2af713b4b36e577181c7946f5e5fda0b4R66-R67), even if the transaction was interrupted.

As for the correction of the drawback described above, I will try to fix it. But I can promise no more than I will do this only with minimal risk of regressions, i.e. if I see such a method.

**Comment by erthink** [comment]
@AskAlexSharov, nonetheless, please write a few words here about the noted drawback is important for LwTG or 'not.

**Comment by AskAlexSharov** [comment]
It's not important bug for TG project. I just will follow your recommendation: 
`Your code is not good, especially the fix.
Instead of drop and re-creating DBI or deleting all records manually, you could just call mdbx_drop(tx, dbi, false) to purge data but leave both key-value table and it's handle.`
