### ISSUE TITLE
In-memory-like behavior on micro datasets

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#181]
We using LMDB with NoMetaSync|NoSync options - to run small app tests which need small (<64Mb) fast db (0 safety requirements). 

LMDB in this configuration doesn't really touching disk much (probably until OS doesn't start evicting page cache). 

Same tests on mdbx with mdbx.NoMetaSync | mdbx.UtterlyNoSync and 64Mb growth step geometry - 10 times slower than same tests on lmdb. 

I think it happening because more intensive/earlier disk touches or because geometry taking place immediately. 

( this issue is absolutely less important than https://github.com/erthink/libmdbx/issues/164 )

**Comment by erthink** [comment]
When you define a geometry, the engine has no other way besides to apply it by following the appropriate steps (i.e. create a 64 Mb database file).

So I can advise advise such options:
- use a different geometry: a minimum initial size and a small increment step, instead of a relatively large fixed size;
- use one temporary database and clean it up, instead of creating a new one every time;
- explicitly create a DB in the `/dev/shm` or `/var/run`;

**Comment by AskAlexSharov** [comment]
Make sense - will try you mr advises next week.
