### ISSUE TITLE
Enhance mdbx_env_stat_ex to return stats whole DB (now returns stats of Main DBI)

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#190]

**Comment by erthink** [comment]
Oh, I remember the whole story.

The main problem is that the legacy API (with which you need to maintain compatibility, because it is used somewhere) did not use a transaction, i.e. the `mdbx_env_stat()` does not accepts a transaction in the parameters.
Therefore, it is only possible to get the snapshot information from a meta pages, but not to total across all the subDB(s).

It's time to think about how to fix it.

**Comment by hiqsociety** [comment]
"Break compatibility" and make it mdbx_env_stat_all(txn)?

**Comment by erthink** [comment]
Please check this fix in your use cases.

**Comment by AskAlexSharov** [comment]
looks good to me

**Comment by AskAlexSharov** [comment]
@hiqsociety released https://github.com/torquem-ch/mdbx-go/releases/tag/v0.10.2
