### ISSUE TITLE
Mdbx doesn't load ntdll

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#196]
```    
// added libmdbx as git submodule
cd libmdbx
mkdir build
 cd build
 cmake -G "MinGW Makefiles" ..
 cmake --build . --target mdbx-static
 cp ./libmdbx-static.a  ./libmdbx.a
// linked by: -L./../libmdbx/build -lmdbx-static
 ```
I see error `osal.c:1522: undefined reference to 'NtClose'`
https://github.com/torquem-ch/mdbx-go/runs/2551855726?check_suite_focus=true#step:4:205

ntdll.dll is in C:\WINDOWS\SYSTEM32 
https://github.com/torquem-ch/mdbx-go/runs/2551855726?check_suite_focus=true#step:4:156

**Comment by erthink** [comment]
MDBX never loads `ntdll.dll` directly, but RTFM https://github.com/erthink/libmdbx#windows "...do not forget to add ntdll.lib to linking."

When using shared mdbx library (`mdbx.dll`), the `ntdll.dll` was already linked/referenced from `mdbx.dll` during mdbx build.

When using static mdbx library, the `ntdll.dll` can't be linked/referenced during mdbx build.
I.e. this is a traditional/usual static library issue - you should link your exe/solib target with all libraries which used by all you are using.

CMake does this automatically, especially when `INTERFACE` keyword is engaged to adding used libraries.
So you if you build your project with CMake you should just add mdbx with it's own `CMakeLists.txt` via subdirectory.
Otherwise if you build `libmdbx.a` separatelly, yo should link with you exe/solib with MS's `ntdll.lib` manually.

**Comment by AskAlexSharov** [comment]
ah, now I see what did you mean. 
Ok, linked ntdll manually and faced conflict - Go's compiler automatically add -lmsvcrt by some reason: 
https://github.com/torquem-ch/mdbx-go/runs/2554391386?check_suite_focus=true#step:4:133

Also did try link to dynamik lib of mdbx, but got `exit status 3221225781`
https://github.com/torquem-ch/mdbx-go/runs/2554820694?check_suite_focus=true#step:5:208

Ok, this is some kind of progress. I will continue suffer tomorrow.

**Comment by AskAlexSharov** [comment]
Sure. Thank.
