### ISSUE TITLE
osx cmake install can't create man folder

### ISSUE THREAD

**Issue by AskAlexSharov** [erthink/libmdbx#209]
after git pull
```
mkdir build
cd build
cmake ..
make install


-- Install configuration: "Release"
-- Installing: /usr/local/lib/libmdbx.dylib
-- Installing: /usr/local/include/mdbx.h
-- Installing: /usr/local/include/mdbx.h++
-- Installing: /usr/local/bin/mdbx_chk
-- Installing: /usr/local/bin/mdbx_stat
-- Installing: /usr/local/bin/mdbx_copy
-- Installing: /usr/local/bin/mdbx_dump
-- Installing: /usr/local/bin/mdbx_load
-- Installing: /usr/local/bin/mdbx_drop
CMake Error at cmake_install.cmake:121 (file):
  file cannot create directory: /usr/local/man/man1.  Maybe need
  administrative privileges.
```
I'm not sure, but I see `ls /usr/share/man/man1` folder on OSX (/usr/share instead of /usr/local)

**Comment by erthink** [comment]
Basically it is default CMake behavior (depending of [`CMAKE_INSTALL_PREFIX`](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html#variable:CMAKE_INSTALL_PREFIX)), but I will try to use `GNUInstallDirs` on non-Windows platforms.

**Comment by erthink** [comment]
@AskAlexSharov, I've minimally fixed some things.
Please check if this fixed the problem in your case.

However, I do not intend to fix anything more in this way, even if the problem still exists.
Because this means that there a some problem is in `CMake` (in the `GNUInstallDirs` module), and/or the `-D` command-line option should be used to explicitly define a corresponding variables responsible for an install directories.

**Comment by AskAlexSharov** [comment]
It's fine to leave it as "wont fix" if workaround described here. 
Tested - works.
