### ISSUE TITLE
MDBX_BAD_VALSIZE when insert into DupSort bucket 

### ISSUE THREAD

**Issue by gcxfd** [erthink/libmdbx#241]
I use nodejs with dupsort ( use @rmw/mdbx , wrapper code is there https://github.com/rmw-lib/node-mdbx )

I found something MDBX_BAD_VALSIZE like this issue https://github.com/erthink/libmdbx/issues/146

the test code is there https://github.com/gcxfd/MDBX_BAD_VALSIZE

I use macos and nodejs 17.0.1

![image](https://user-images.githubusercontent.com/69608605/141451878-71248de1-f744-44f0-a3e4-103bed1dc01d.png)

**Comment by erthink** [comment]
I think this is issue of the particular binding', but not libmdbx, since the described above scenario is trivial usual usecase and thus is well tested (contrast to the issue you are referring to).

Anyway to deal with the issue, I need a reproducing scenario without using third-party bindings code, or at least using third-party code (which was) sufficient checked for the absence of trivial errors.

So please submit issue to Nodejs binding' origin repo (I will try to transfer this one).

**Comment by gcxfd** [comment]
@erthink I write a C demo there  https://github.com/gcxfd/libmdbx/blob/master/example/example-mdbx.c

the same error

you can the diff there
https://github.com/erthink/libmdbx/compare/master...gcxfd:master

![image](https://user-images.githubusercontent.com/69608605/141492297-5046aba3-ea1a-4765-b1ee-ed75e6891d91.png)

**Comment by gcxfd** [comment]
I fixed this by remove MDBX_DUPFIXED

**Comment by erthink** [comment]
Your problem is using `MDBX_DUPFIXED` with different lengths of data items.
Therefore, I have just clarified the description of [`MDBX_DUPFIXED`](https://erthink.github.io/libmdbx/group__c__dbi.html#ggafe3bddb297b3ab0d828a487c5726f76aa8517d5462fff6156349985b9366b56a4).
