### ISSUE TITLE
MDBX_SAFE_NOSYNC clarification

### ISSUE THREAD

**Issue by kriszyp** [erthink/libmdbx#266]
I wanted to clarify how `MDBX_SAFE_NOSYNC` works. My understanding is that with `MDBX_SAFE_NOSYNC` enabled, committing a write txn will update a meta page to point to the latest transaction, but that transaction referenced in the meta page will be marked as transient/unsafe until there is a sync/full operation at some point in the future than then transitions the state of the transaction to being considered truly durable/safe. I thought that distinguishing transactions that aren't fully flushed was essential to ensuring that when restarting the database, it doesn't reference any pages that were potentially unwritten (and thus corrupt).

Consequently, I would expect that if I write some data in transaction, commit it, then exit the process without performing a sync/flush (via mdbx_env_sync, periodic syncing, or threshold syncing), and then restart the process, that that transaction would _not_ be visible/accessible since it could be referencing unflushed pages. However, the latest transaction data does seem to visible and accessible even with a sync/flush in the prior process. Is that because libmdbx has some way of checking/verifying the latest unflushed transactions to determine if all the pages really did end up getting written? Or is there something that performs sync/flushes after transactions are committed even if I don't explicitly set it up?

**Comment by erthink** [comment]
libmdbx uses the "boot id" (for instance the `/proc/sys/kernel/random/boot_id`) for solve this.

Briefly, is bootid stored in a weak-marked meta-page is match the current system bootid then no reboot or system/power failure was since this weak-meta was writen. In this case we can hope than all unflushed-to-disk data are still live in memory, etc.

The next major point is libmdbx have the three meta pages, but not the two. Thus it is possible to interleave-rewrite two meta-pages as a weak, while a third could stay/hold the last steady point.

And the last point is libmdbx don't reclaims the GC' records which are beyond the lastest steady-makred txn, i.e. don't recycle the pages which are constitute/included_in the latest steady MVCC-snapshot.

A PR(s) for clarification is(are) welcome!
https://github.com/erthink/libmdbx/blob/4e2a7465ab9765d9c1d93697c5100b6f6898f64e/mdbx.h#L1158-L1330

**Comment by kriszyp** [comment]
Thank you for the clarification, that makes perfect sense! I didn't know about boot ids, that's a great technique!

**Comment by kriszyp** [comment]
Actually, I am still not sure I am understanding how this is supposed to work. I thought `MDBX_SAFE_NOSYNC` should avoid sync operations in commits. However when I enable `MDBX_SAFE_NOSYNC` for an env and set a breakpoint in mdbx_fsync, I still see a lot of calls to mdbx_fsync from mdbx_sync_locked < mdbx_txn_commit_ex < mdbx_txn_commit_ex < mdbx_txn_commit when committing write txns. Am I doing something wrong with how I am using `MDBX_SAFE_NOSYNC` or misunderstanding its intention?

**Comment by erthink** [comment]
The picture is a bit more complex.
With the `MDBX_SAFE_NOSYNC` option the `mdbx_sync()` or `mdbx_msync()`  will be called in the following cases:
- during commit if a threshold set by `mdbx_env_set_syncbytes()` or `mdbx_env_set_syncperiod()` was reacheв;
- during the commit before shrinking the DB, if there appropriate conditions are; 
- during page allocation (both as while changing data as during commit) if there no free pages and a such sync will unhold GC recycling.
- explicit cases: calls `mdbx_env_sync_ex()`, `mdbx_env_sync_poll()`, `mdbx_env_set_geometry()`, closing DB, etc.

Just in case, I checked the behavior, but I didn't see any extra sync calls.

**Comment by kriszyp** [comment]
Thank you again for your explanations, appreciate it!
