### ISSUE TITLE
The <sys/vmmeter.h> header is missing in iOS SDK

### ISSUE THREAD

**Issue by erthink** [erthink/libmdbx#92]

**Comment by snej** [comment]
FYI I've just filed a bug report with Apple about this, and referenced lmbmdbx as an example of a 3rd party library whose build breaks as a result.

**Comment by snej** [comment]
Also FYI, it's not even necessary to include this header on Apple platforms. It's only needed for the `struct vmtotal info` declaration at core.c:9857, which is not compiled on Apple because the earlier `#elif defined(__MACH__)` section is used instead.

So you could fix the problem by wrapping the `#include` like so:
```c
#ifndef __MACH__
#include <sys/vmmeter.h>
#endif 
```

**Comment by erthink** [comment]
@snej, thanks.

As far as I remember, there were some necessary definitions.
But I have redone it several times (in particular [this code](https://github.com/erthink/libmdbx/blob/19454f26e6a258b4ec7306dcb94a3483538cbf72/src/elements/core.c#L9832-L9840)).
Let me check.

**Comment by snej** [comment]
FYI, Apple just notified me that they've fixed the bug I reported. `<sys/vmmeter.h>` is present in the iOS 14 SDK (part of Xcode 12.)
